import { describe, expect, it } from 'vitest'
import { buildHermesOperatorBrief } from '@/lib/hermes-operator/brief'
import type { HermesOperatorContextSnapshot } from '@/lib/hermes-operator/types'

const baseContext: HermesOperatorContextSnapshot = {
  generatedAt: '2026-06-01T09:00:00.000Z',
  revenue: {
    conversions: {
      overview: {
        contacted: 24,
        replied: 8,
        qualifiedReplies: 4,
        meetingsBooked: 2,
        checkoutsCreated: 2,
        wonCount: 2,
        paidCount: 1,
        paidCashEur: 1800,
        replyRate: 33.3,
        qualifiedRate: 16.7,
        closeRate: 4.2,
        wonToPaidRate: 50,
        replyToPaidRate: 12.5,
        leadToReplyHours: 12,
        replyToCloseDays: 5,
      },
      offerBreakdown: [],
      angleBreakdown: [],
      segmentOfferBreakdown: [],
      modelBreakdown: [],
      bestOffer: null,
      bestOfferToWin: {
        contacted: 8,
        replied: 4,
        qualifiedReplies: 2,
        meetingsBooked: 1,
        checkoutsCreated: 1,
        wonCount: 1,
        paidCount: 0,
        paidCashEur: 0,
        replyRate: 50,
        qualifiedRate: 25,
        closeRate: 0,
        wonToPaidRate: 0,
        replyToPaidRate: 0,
        offerId: 'offer-win',
        offerName: 'Solo CFO Sprint',
        offerVariant: 'win',
      },
      bestOfferToCollectCash: {
        contacted: 10,
        replied: 5,
        qualifiedReplies: 3,
        meetingsBooked: 2,
        checkoutsCreated: 2,
        wonCount: 2,
        paidCount: 1,
        paidCashEur: 1800,
        replyRate: 50,
        qualifiedRate: 30,
        closeRate: 10,
        wonToPaidRate: 50,
        replyToPaidRate: 20,
        offerId: 'offer-cash',
        offerName: 'Revenue Audit',
        offerVariant: 'cash',
      },
      bestAngle: {
        contacted: 10,
        replied: 5,
        qualifiedReplies: 3,
        meetingsBooked: 2,
        checkoutsCreated: 2,
        wonCount: 2,
        paidCount: 1,
        paidCashEur: 1800,
        replyRate: 50,
        qualifiedRate: 30,
        closeRate: 10,
        wonToPaidRate: 50,
        replyToPaidRate: 20,
        key: 'offer-cash:roi-first',
        offerId: 'offer-cash',
        offerName: 'Revenue Audit',
        angle: 'roi-first',
      },
      bestSegmentToReply: null,
      bestSegmentToPay: {
        contacted: 6,
        replied: 3,
        qualifiedReplies: 2,
        meetingsBooked: 1,
        checkoutsCreated: 1,
        wonCount: 1,
        paidCount: 1,
        paidCashEur: 1800,
        replyRate: 50,
        qualifiedRate: 33.3,
        closeRate: 16.7,
        wonToPaidRate: 100,
        replyToPaidRate: 33.3,
        key: 'reddit:warm:offer-cash',
        source: 'reddit',
        band: 'warm',
        offerId: 'offer-cash',
        offerName: 'Revenue Audit',
      },
      segmentRepliesNoPay: {
        contacted: 8,
        replied: 4,
        qualifiedReplies: 2,
        meetingsBooked: 1,
        checkoutsCreated: 1,
        wonCount: 0,
        paidCount: 0,
        paidCashEur: 0,
        replyRate: 50,
        qualifiedRate: 25,
        closeRate: 0,
        wonToPaidRate: 0,
        replyToPaidRate: 0,
        key: 'linkedin:hot:offer-win',
        source: 'linkedin',
        band: 'hot',
        offerId: 'offer-win',
        offerName: 'Solo CFO Sprint',
      },
      segmentWinsNoCash: null,
      sourceClosesFastest: null,
      sourceCollectsFastest: {
        contacted: 6,
        replied: 3,
        qualifiedReplies: 2,
        meetingsBooked: 1,
        checkoutsCreated: 1,
        wonCount: 1,
        paidCount: 1,
        paidCashEur: 1800,
        replyRate: 50,
        qualifiedRate: 33.3,
        closeRate: 16.7,
        wonToPaidRate: 100,
        replyToPaidRate: 33.3,
        source: 'reddit',
        leadToReplyHours: 8,
        replyToCloseDays: 4,
      },
      bestModel: null,
      messageFamilyBreakdown: [],
      bestMessageFamily: {
        messageFamily: 'roi-first',
        messageKey: 'roi-first:initial:reddit',
        contacted: 6,
        replied: 3,
        wonCount: 1,
        paidCount: 1,
        paidCashEur: 1800,
        replyRate: 50,
        winRate: 16.7,
        paidRate: 16.7,
        topObjection: 'timing',
        objectionCount: 2,
      },
      messageFamilyRepliesNoCash: {
        messageFamily: 'founder-pain',
        messageKey: 'founder-pain:initial:linkedin',
        contacted: 8,
        replied: 4,
        wonCount: 0,
        paidCount: 0,
        paidCashEur: 0,
        replyRate: 50,
        winRate: 0,
        paidRate: 0,
        topObjection: 'budget',
        objectionCount: 3,
      },
      messageFamilyWinsNoCash: null,
      messageFamilyTopObjection: {
        messageFamily: 'founder-pain',
        messageKey: 'founder-pain:initial:linkedin',
        contacted: 8,
        replied: 4,
        wonCount: 0,
        paidCount: 0,
        paidCashEur: 0,
        replyRate: 50,
        winRate: 0,
        paidRate: 0,
        topObjection: 'budget',
        objectionCount: 3,
      },
      commonObjections: [{ type: 'budget', count: 3 }],
      lostReasons: [{ type: 'timing', count: 2 }],
      repeatNext: {
        title: 'Repeat reddit warm',
        detail: 'This segment is collecting cash fastest.',
      },
      stopNext: {
        title: 'Stop founder-pain on linkedin hot',
        detail: 'Replies exist but do not collect cash.',
      },
    },
    weeklyReview: {
      window: { weekStart: '2026-05-26', weekEnd: '2026-06-01', label: '2026-05-26 → 2026-06-01' },
      bestSource: { title: 'reddit', detail: '1 paid · 4d reply→cash', source: 'reddit' },
      bestSegment: { title: 'linkedin/hot · Solo CFO Sprint', detail: '4 replies · 0 paid', source: 'linkedin', band: 'hot' },
      bestOffer: { title: 'Revenue Audit', detail: '1 paid · 1800€ collected' },
      bestOfferByCash: { title: 'Revenue Audit', detail: '1800€ attributed cash · 1 paid' },
      bestAngle: { title: 'Revenue Audit · roi-first', detail: '1 paid · 50% reply' },
      bestAngleByCash: { title: 'Revenue Audit · roi-first', detail: '1800€ attributed cash · 1 paid' },
      bestMessageFamily: { title: 'roi-first', detail: '1 paid · 50% reply' },
      messageFamilyToStop: { title: 'founder-pain', detail: '4 replies but 0 paid' },
      topObjection: { title: 'budget', detail: 'founder-pain · 3 occurrences this week' },
      highestValueObjection: { title: 'budget', detail: 'founder-pain blocks 0€ cash path' },
      mainLeak: { stageKey: 'meeting_to_close', title: 'Meeting → close', detail: '1 prospects lost here · 2 meetings · 1 paid' },
      nextExperiment: { focus: 'message_family', title: 'Tighten family founder-pain', detail: 'This family replies but does not convert to paid cash yet.' },
    },
    outcomes: {
      last7d: { replies: 5, deals: 2, cashEur: 1800 },
      previous7d: { replies: 3, deals: 1, cashEur: 600 },
      last30d: { replies: 9, deals: 3, cashEur: 2400 },
      previous30d: { replies: 4, deals: 1, cashEur: 600 },
      delta7d: { replies: 2, deals: 1, cashEur: 1200 },
      delta30d: { replies: 5, deals: 2, cashEur: 1800 },
      rates: { replyRate7d: 33.3, winRate7d: 13.3, replyRate30d: 30, winRate30d: 10 },
      sourceBreakdown: [],
      sourceBandBreakdown: [],
      topSegment: null,
      blockers: [],
      blockerActions: [],
    },
    loop: {
      activeLoops: 2,
      readyCheckouts: 1,
      pendingApprovals: 2,
      revenueEur: 1800,
      blockedRevenueEur: 900,
      recommendedAction: null,
    },
  },
  prospects: {
    total: 24,
    awaitingApproval: 2,
    pendingApprovals: 2,
    followUpsDue: 5,
    hotLeads: 6,
  },
  automation: {
    autonomyStatus: 'active',
    pausedReason: null,
    queuedJobs: 3,
    runningJobs: 1,
    failedJobs: 1,
  },
  infrastructure: {
    status: 'degraded',
    headline: 'Qdrant unstable',
    summary: 'One dependency is degrading throughput.',
    operatorNextStep: 'Run diagnostics now.',
    checkedAt: '2026-06-01T08:55:00.000Z',
    runtimeCommit: 'abc123',
    servicesCount: 6,
    openIncidents: 1,
  },
}

describe('buildHermesOperatorBrief', () => {
  it('builds a cash-first daily brief from Hermes context and deltas', () => {
    const brief = buildHermesOperatorBrief({
      userId: 'user-1',
      runId: 'run-1',
      context: baseContext,
      runDelta: {
        replied: 2,
        paid: 1,
        followUpsDue: 3,
        pendingApprovals: -1,
        queuedJobs: 1,
        failedJobs: 1,
      },
      now: new Date('2026-06-01T09:00:00.000Z'),
    })

    expect(brief.summary).toContain('Revenue Audit leads cash')
    expect(brief.summary).toContain('Block cash:')
    expect(brief.summary).toContain('Stop:')
    expect(brief.cashDelta7d).toBe(1200)
    expect(brief.topBlocker).toContain('approvals are blocking outbound')
    expect(brief.topOpportunity).toContain('approval-gated drafts')
    expect(brief.bestOffer).toBe('Revenue Audit')
    expect(brief.bestSegment).toBe('reddit/warm')
    expect(brief.bestSource).toBe('reddit')
    expect(brief.mainLeak).toContain('Meeting')
    expect(brief.nextBestAction).toContain('Clear 2 approvals')
  })
})
